# Generated by Django 3.2.7 on 2021-09-18 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_auto_20210918_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('Cse', 'Cse'), ('Ece', 'Ece'), ('Eee', 'Eee'), ('Mech', 'Mech'), ('Chem', 'Chem'), ('Civil', 'Civil'), ('Bio', 'Bio'), ('Mme', 'Mme')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(blank=True, choices=[('Oc', 'Oc'), ('Obc', 'Obc'), ('Sc', 'Sc'), ('St', 'St')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_profile',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
